version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/mjml2html

    environment:
      PORT: 3001

    steps:
      - checkout

      - run: npm ci

      # Run the API server
      - run:
          name: Running API server
          command: npm start
          background: true

      # Wait for the server to start responding.
      - run:
          command: |
            dockerize -wait tcp://127.0.0.1:3001 -timeout 1m
            curl http://0.0.0.0:3001

      # Run the tests
      - run: npm test
  
  misc:
    docker:
      - image: circleci/node:10

    working_directory: ~/mjml2html

    steps:
      - checkout

      - run: npm ci

      - run:
        name: Audit for vulnerabilities
        command: npm audit --audit-level=moderate

workflows:
  version: 2
  mjml2html:
    jobs:
      - misc
      - build
