version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/mjml2html

    environment:
      PORT: 3001

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Running API server
          command: npm start
          background: true

      - run:
          name: Wait for the API server
          command: |
            dockerize -wait tcp://127.0.0.1:3001 -timeout 1m
            curl http://0.0.0.0:3001

      - run:
          name: Run tests
          command: npm test
  
  misc:
    docker:
      - image: circleci/node:10

    working_directory: ~/mjml2html

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Audit for vulnerabilities
          command: npm audit --audit-level=moderate

workflows:
  version: 2
  mjml2html:
    jobs:
      - misc
      - build
